# Generated by Django 4.0.3 on 2022-07-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_xabarlar_alter_loyihalar_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xabarlar',
            name='text',
            field=models.TextField(),
        ),
    ]
