# Generated by Django 4.0.3 on 2022-07-30 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_xabarlar_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='xabarlar',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
